DROP TABLE IF EXISTS `BOC_gongdanHis`;
CREATE TABLE `BOC_gongdanHis` (
  `id` char(36) NOT NULL COMMENT 'uuid',
  `gongdanId` varchar(16) DEFAULT NULL COMMENT '服务请求编号',
  `customerCallTime` datetime DEFAULT '0000-00-00 00:00:00' COMMENT '客户来电时间',
  `callInNum` varchar(36)  DEFAULT '' COMMENT '呼入号码',
  `gongdanSource` varchar(100)  DEFAULT '' COMMENT '来源',
  `organize` varchar(36)  DEFAULT '' COMMENT '组织',
  `gongdanLevel` varchar(36)  DEFAULT '' COMMENT '服务请求级别',
  `belongBank` varchar(100)  DEFAULT '' COMMENT '所属分行',
  `channelName` varchar(36)  DEFAULT '' COMMENT '渠道名称',
  `country` varchar(36)  DEFAULT '' COMMENT '国家',
  `gongdanState` varchar(36)  DEFAULT '' COMMENT '工单状态',
  `gongdanType` varchar(36)  DEFAULT '' COMMENT '类型',
  `customerName` varchar(100)  DEFAULT '' COMMENT '客户姓名',
  `companyFullName` varchar(100)  DEFAULT '' COMMENT '公司全称',
  `businessWorkType` varchar(64)  DEFAULT '' COMMENT '业务活动类型',
  `businessWorkChildType` varchar(64)  DEFAULT '' COMMENT '业务活动子类型',   
  `customerSex` varchar(4)  DEFAULT '' COMMENT '客户性别',
  `paperType` varchar(64)  DEFAULT '' COMMENT '证件类型',
  `paperNum` varchar(64)  DEFAULT '' COMMENT '证件号码',
  `phoneNum` varchar(64)  DEFAULT '' COMMENT '联系电话',
  `email` varchar(36)  DEFAULT '' COMMENT '邮件地址',
  `huifuMgs` varchar(2000)  DEFAULT '' COMMENT '回复意见',
  `tuihuiMgs` varchar(2000)  DEFAULT '' COMMENT '退回意见',
  `fuheMgs` varchar(2000)  DEFAULT '' COMMENT '复核意见',
  `chuliMgs` varchar(2000)  DEFAULT '' COMMENT '处理结果',
  `manager` varchar(36)  DEFAULT '' COMMENT '处理人',
  `referDept` varchar(100)  DEFAULT ''COMMENT '涉及部门',
  `defendant` varchar(36)  DEFAULT '' COMMENT '被投诉人',
  `complainType` varchar(36)  DEFAULT '' COMMENT '投诉类型',
  `manageTimeLimit` varchar(36)  DEFAULT '' COMMENT '处理时限',
  `matter` varchar(80)  DEFAULT '' COMMENT '内容',
  `problemType` varchar(36)  DEFAULT '' COMMENT '问题类型',
  `praise` varchar(36)  DEFAULT '' COMMENT '被表扬/建议人',
  `businessType` varchar(36)  DEFAULT '' COMMENT '业务类型',
  `referMan` varchar(36)  DEFAULT '' COMMENT '涉及人员',
  `accountType` varchar(100)  DEFAULT '' COMMENT '账户类型',
  `accountNumber` varchar(100)  DEFAULT '' COMMENT '账户账号',
  `subscribeType` varchar(100)  DEFAULT '' COMMENT '预约类型',
  `manageTime` datetime DEFAULT '0000-00-00 00:00:00' COMMENT '预处理时间',
  `manageSite` varchar(100)  DEFAULT '' COMMENT '预处理地点',
  `replaceAgent` varchar(36)  DEFAULT '' COMMENT '代办人姓名',
  `replaceAgentPaperNum` varchar(36)  DEFAULT '' COMMENT '代办人证件号码',
  `chuangjianrenId` varchar(36)  DEFAULT '' '创建者id',
  `chuangjianrenName` varchar(36) DEFAULT '' COMMENT '创建者名字',
  `chuangjianTime`datetime DEFAULT '0000-00-00 00:00:00' COMMENT '  创建时间',
  `fuherenId` varchar(100)  DEFAULT '' COMMENT '复核者ID',
  `fuherenName` varchar(100)  DEFAULT '' COMMENT '复核者名字',
  `fuheTime` datetime DEFAULT '0000-00-00 00:00:00' COMMENT '复核时间',  
  `wanchengrenId` varchar(100)  DEFAULT '' COMMENT '完成人ID',
  `wanchengrenName` varchar(100)  DEFAULT '' COMMENT '完成人名字',
  `wanchengTime` datetime DEFAULT '0000-00-00 00:00:00' COMMENT '完成时间',
  `disponseUser` varchar(200) DEFAULT '' COMMENT '当前处理人',
  `disponseBTime` datetime DEFAULT '0000-00-00 00:00:00' COMMENT '处理人开始处理时间',
  `disponseETime` datetime DEFAULT '0000-00-00 00:00:00' COMMENT '处理时间结束时间',
  `endDealTime` datetime DEFAULT '0000-00-00 00:00:00' COMMENT '最后操作时间',
  `companyId` varchar(50) DEFAULT '' COMMENT '公司id',
  `companyName` varchar(200) DEFAULT '' COMMENT '公司名称',
  `departmentId` varchar(200) DEFAULT '' COMMENT '部门id',
  `departmentName` varchar(200) DEFAULT '' COMMENT '部门名称',
  `flowNode` varchar(36)  DEFAULT '' COMMENT '节点名称',
  `flowId` varchar(36) DEFAULT '' COMMENT '流程标识',
  `guanlianId` varchar(36) DEFAULT '' COMMENT '关联工单标识',
  PRIMARY KEY (`id`)
)  ENGINE=MyISAM DEFAULT CHARSET=gbk;